// Copyright (c) 2026 EvolveOS Software
//
// Licensed under the MIT License. 
// See the LICENSE file in the project root for more information.

namespace EvolveOS_Optimizer.Utilities.WinBuilder
{
    public static class EvolveOSCatalog
    {
        public static List<RemovableApp> GetAvailableApps()
        {
            return new List<RemovableApp>
            {
                // Core Windows Apps
                new RemovableApp { DisplayName = "3D Viewer", PackageName = "Microsoft.Microsoft3DViewer" },
                new RemovableApp { DisplayName = "Alarms & Clock", PackageName = "Microsoft.WindowsAlarms" },
                new RemovableApp { DisplayName = "Calculator", PackageName = "Microsoft.WindowsCalculator" },
                new RemovableApp { DisplayName = "Camera", PackageName = "Microsoft.WindowsCamera" },
                new RemovableApp { DisplayName = "Clipchamp", PackageName = "Clipchamp.Clipchamp" },
                new RemovableApp { DisplayName = "Copilot (All Components)", PackageName = "Copilot" },
                new RemovableApp { DisplayName = "Cortana", PackageName = "Microsoft.549981C3F5F10" },
                new RemovableApp { DisplayName = "Dev Home", PackageName = "Microsoft.Windows.DevHome" },
                new RemovableApp { DisplayName = "Feedback Hub", PackageName = "Microsoft.WindowsFeedbackHub" },
                new RemovableApp { DisplayName = "Get Help", PackageName = "Microsoft.GetHelp" },
                new RemovableApp { DisplayName = "Get Started (Tips)", PackageName = "Microsoft.Getstarted" },
                new RemovableApp { DisplayName = "Mail & Calendar", PackageName = "microsoft.windowscommunicationsapps" },
                new RemovableApp { DisplayName = "Maps", PackageName = "Microsoft.WindowsMaps" },
                new RemovableApp { DisplayName = "Microsoft Family", PackageName = "MicrosoftCorporationII.MicrosoftFamily" },
                new RemovableApp { DisplayName = "Microsoft Store", PackageName = "Microsoft.WindowsStore" },
                new RemovableApp { DisplayName = "Mixed Reality Portal", PackageName = "Microsoft.MixedReality.Portal" },
                new RemovableApp { DisplayName = "Notepad", PackageName = "Microsoft.WindowsNotepad" },
                new RemovableApp { DisplayName = "Office Hub (Microsoft 365)", PackageName = "Microsoft.MicrosoftOfficeHub" },
                new RemovableApp { DisplayName = "OneNote", PackageName = "Microsoft.Office.OneNote" },
                new RemovableApp { DisplayName = "Outlook for Windows", PackageName = "Microsoft.OutlookForWindows" },
                new RemovableApp { DisplayName = "Paint (Modern)", PackageName = "Microsoft.Paint" },
                new RemovableApp { DisplayName = "People", PackageName = "Microsoft.People" },
                new RemovableApp { DisplayName = "Photos", PackageName = "Microsoft.Windows.Photos" },
                new RemovableApp { DisplayName = "Power Automate", PackageName = "Microsoft.PowerAutomateDesktop" },
                new RemovableApp { DisplayName = "Quick Assist", PackageName = "MicrosoftCorporationII.QuickAssist" },
                new RemovableApp { DisplayName = "Skype", PackageName = "Microsoft.SkypeApp" },
                new RemovableApp { DisplayName = "Snipping Tool (Screen Sketch)", PackageName = "Microsoft.ScreenSketch" },
                new RemovableApp { DisplayName = "Solitaire Collection", PackageName = "Microsoft.MicrosoftSolitaireCollection" },
                new RemovableApp { DisplayName = "Sound Recorder", PackageName = "Microsoft.WindowsSoundRecorder" },
                new RemovableApp { DisplayName = "Sticky Notes", PackageName = "Microsoft.MicrosoftStickyNotes" },
                new RemovableApp { DisplayName = "Teams", PackageName = "MSTeams" },
                new RemovableApp { DisplayName = "To Do", PackageName = "Microsoft.Todos" },
                new RemovableApp { DisplayName = "Xbox App (Legacy)", PackageName = "Microsoft.XboxApp" },
                new RemovableApp { DisplayName = "Xbox App (Modern)", PackageName = "Microsoft.GamingApp" },
                new RemovableApp { DisplayName = "Xbox Game Bar", PackageName = "Microsoft.XboxGamingOverlay" },
                new RemovableApp { DisplayName = "Xbox Game Overlay", PackageName = "Microsoft.XboxGameOverlay" },
                new RemovableApp { DisplayName = "Xbox Identity Provider", PackageName = "Microsoft.XboxIdentityProvider" },
                new RemovableApp { DisplayName = "Xbox TCUI", PackageName = "Microsoft.Xbox.TCUI" },
                new RemovableApp { DisplayName = "Xbox Speech To Text", PackageName = "Microsoft.XboxSpeechToTextOverlay" },
                new RemovableApp { DisplayName = "Your Phone (Phone Link)", PackageName = "Microsoft.YourPhone" },
                new RemovableApp { DisplayName = "Zune Music (Media Player)", PackageName = "Microsoft.ZuneMusic" },
                new RemovableApp { DisplayName = "Zune Video (Movies & TV)", PackageName = "Microsoft.ZuneVideo" },

                // Third-Party Sponsor Bloatware (Using wildcards)
                new RemovableApp { DisplayName = "Bing News", PackageName = "BingNews" },
                new RemovableApp { DisplayName = "Bing Search", PackageName = "BingSearch" },
                new RemovableApp { DisplayName = "Bing Weather", PackageName = "BingWeather" },
                new RemovableApp { DisplayName = "Disney+", PackageName = "Disney" },
                new RemovableApp { DisplayName = "Facebook", PackageName = "Facebook" },
                new RemovableApp { DisplayName = "Instagram", PackageName = "Instagram" },
                new RemovableApp { DisplayName = "LinkedIn (Legacy)", PackageName = "LinkedInforWindows" },
                new RemovableApp { DisplayName = "LinkedIn (Modern)", PackageName = "7EE7776C.LinkedInforWindows" },
                new RemovableApp { DisplayName = "Netflix", PackageName = "Netflix" },
                new RemovableApp { DisplayName = "Prime Video", PackageName = "PrimeVideo" },
                new RemovableApp { DisplayName = "Spotify", PackageName = "Spotify" },
                new RemovableApp { DisplayName = "TikTok", PackageName = "TikTok" },
                new RemovableApp { DisplayName = "WhatsApp", PackageName = "WhatsApp" }
            };
        }

        public static List<RegistryTweak> GetAvailableTweaks()
        {
            return new List<RegistryTweak>
            {
                // ===================== POWER SETTINGS =====================
                new RegistryTweak { Category = "Power", Description = "Disable Hibernation (Saves disk space)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\" /v \"HibernateEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Power", Description = "Disable Fast Startup (Hiberboot)", RegCommand = "reg add \"HKLM\\SYSTEM\\ControlSet001\\Control\\Session Manager\\Power\" /v \"HiberbootEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Power", Description = "Hide Hibernate Option in Start Menu", RegCommand = "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FlyoutMenuSettings\" /v \"ShowHibernateOption\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Power", Description = "Disable Power Throttling", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\\PowerThrottling\" /v \"PowerThrottlingOff\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Power", Description = "Hide Lock Option in Start Menu", RegCommand = "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FlyoutMenuSettings\" /v \"ShowLockOption\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Power", Description = "Hide Sleep Option in Start Menu", RegCommand = "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FlyoutMenuSettings\" /v \"ShowSleepOption\" /t REG_DWORD /d 0 /f" },

                // ===================== GAMING & PERFORMANCE =====================
                new RegistryTweak { Category = "Gaming & Performance", Description = "Disable Background Apps", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy\" /v \"LetAppsRunInBackground\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Disable Storage Sense Globally", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\StorageSense\" /v \"AllowStorageSenseGlobal\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Optimize CPU for Background Services (Win32PrioritySeparation)", RegCommand = "reg add \"HKLM\\System\\CurrentControlSet\\Control\\PriorityControl\" /v \"Win32PrioritySeparation\" /t REG_DWORD /d 38 /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Set System Responsiveness to 10 (Gaming)", RegCommand = "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\" /v \"SystemResponsiveness\" /t REG_DWORD /d 10 /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Give Games Higher CPU Priority", RegCommand = "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"Priority\" /t REG_DWORD /d 6 /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Set Games to High Scheduling Category", RegCommand = "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"Scheduling Category\" /t REG_SZ /d \"High\" /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Give Games Higher GPU Priority", RegCommand = "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"GPU Priority\" /t REG_DWORD /d 8 /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Let GPU Manage Memory (HwSchMode)", RegCommand = "reg add \"HKLM\\System\\CurrentControlSet\\Control\\GraphicsDrivers\" /v \"HwSchMode\" /t REG_DWORD /d 2 /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Enable Legacy NVIDIA Image Sharpening (Older Drivers)", RegCommand = "reg add \"HKLM\\Software\\NVIDIA Corporation\\Global\\FTS\" /v \"EnableGR535\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Set Network Throttling Index to 10 (Gaming)", RegCommand = "reg add \"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\" /v \"NetworkThrottlingIndex\" /t REG_DWORD /d 10 /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Disable Network Packet Buffering (TcpAckFrequency)", RegCommand = "reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\" /v \"TcpAckFrequency\" /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Disable TCP No Delay Buffering", RegCommand = "reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\" /v \"TCPNoDelay\" /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Disable Xbox Game DVR (Improves FPS)", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR\" /v \"AllowGameDVR\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Reduce Services Pipe Timeout (Faster Boot)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\" /v \"ServicesPipeTimeout\" /t REG_DWORD /d 30000 /f" },
                new RegistryTweak { Category = "Gaming & Performance", Description = "Preload Boot Files (HDD Prefetcher)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters\" /v \"EnablePrefetcher\" /t REG_DWORD /d 3 /f" },

                // ===================== ADVANCED SERVICES (NEW) =====================
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Diagnostic Policy Service (DPS)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\DPS\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Diagnostic Service Host (WdiServiceHost)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\WdiServiceHost\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Diagnostic System Host (WdiSystemHost)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\WdiSystemHost\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Distributed Link Tracking Client (TrkWks)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\TrkWks\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable TCP/IP NetBIOS Helper (lmhosts)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\lmhosts\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Superfetch/SysMain (For SSDs)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\SysMain\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Windows Search Indexing", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\WSearch\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Print Spooler (If no printer used)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\Spooler\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable DiagTrack (Telemetry Service)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\DiagTrack\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Program Compatibility Assistant (PcaSvc)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\PcaSvc\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Windows Error Reporting Service (WerSvc)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\WerSvc\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Location Tracking Service (lfsvc)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\lfsvc\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Retail Demo Service", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\RetailDemo\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Windows Insider Service (wisvc)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\wisvc\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Telephony Service (PhoneSvc)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\PhoneSvc\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Wallet Service", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\WalletService\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Smart Card Reader Service", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\SCardSvr\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Smart Card Device Enumeration", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\ScDeviceEnum\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Smart Card Policy Service", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\SCPolicySvc\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set Maps Broker to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\MapsBroker\" /v \"Start\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Fax Service", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\Fax\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Disable Windows Media Player Network Sharing", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\WMPNetworkSvc\" /v \"Start\" /t REG_DWORD /d 4 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set Mixed Reality OpenXR to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\MixedRealityOpenXRSvc\" /v \"Start\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set Internet Connection Sharing to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\icssvc\" /v \"Start\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set SMS Router to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\SmsRouter\" /v \"Start\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set Parental Controls (WpcMonSvc) to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\WpcMonSvc\" /v \"Start\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set Payment & NFC Manager to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\SEMgrSvc\" /v \"Start\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set Storage Verification (svsvc) to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\svsvc\" /v \"Start\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set Remote Desktop Services to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\TermService\" /v \"Start\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set Xbox Live Auth Manager to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\XblAuthManager\" /v \"Start\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set Xbox Live Game Save to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\XblGameSave\" /v \"Start\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set Biometric Service (Windows Hello) to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\WbioSrvc\" /v \"Start\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set Tablet Input Service to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\TabletInputService\" /v \"Start\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Services (Advanced Disable)", Description = "Set Sensor Monitoring Service to Manual", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\SensrSvc\" /v \"Start\" /t REG_DWORD /d 3 /f" },

                // ===================== NOTIFICATIONS =====================
                new RegistryTweak { Category = "Notifications", Description = "Disable System Toast Notifications", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\PushNotifications\" /v \"ToastEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable Notification Sounds", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Notifications\\Settings\" /v \"NOC_GLOBAL_SETTING_ALLOW_NOTIFICATION_SOUND\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Hide Toasts Above Lock Screen", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Notifications\\Settings\" /v \"NOC_GLOBAL_SETTING_ALLOW_TOASTS_ABOVE_LOCK\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable Lock Screen Notifications", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\PushNotifications\" /v \"LockScreenToastEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Hide Critical Toasts Above Lock", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Notifications\\Settings\" /v \"NOC_GLOBAL_SETTING_ALLOW_CRITICAL_TOASTS_ABOVE_LOCK\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Hide Notification Bell Icon in Tray", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v \"ShowNotificationIcon\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable 'What's New' Tips (310093)", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"SubscribedContent-310093Enabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable Windows Setup Suggestions (Scoobe)", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\UserProfileEngagement\" /v \"ScoobeSystemSettingEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable Helpful Tips (338389)", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"SubscribedContent-338389Enabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable Action Center Suggestions", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"SystemPaneSuggestionsEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable Capability Access Notifications", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Notifications\\Settings\\Windows.SystemToast.CapabilityAccess\" /v \"Enabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable App Startup Notifications", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Notifications\\Settings\\Windows.SystemToast.StartupApp\" /v \"Enabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Enable Global Location Prompts", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\location\" /v \"ShowGlobalPrompts\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable Daylight Saving Time Notification", RegCommand = "reg add \"HKCU\\Control Panel\\Desktop\" /v \"DstNotification\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable Defender Center Notifications", RegCommand = "reg add \"HKCU\\Software\\Policies\\Microsoft\\Windows Defender Security Center\\Notifications\" /v \"DisableNotifications\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable Enhanced Defender Notifications", RegCommand = "reg add \"HKCU\\Software\\Policies\\Microsoft\\Windows Defender Security Center\\Notifications\" /v \"DisableEnhancedNotifications\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Enable Security & Maintenance Action Center", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Notifications\\Settings\\Windows.SystemToast.SecurityAndMaintenance\" /v \"Enabled\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable Defender Notifications (HKLM)", RegCommand = "reg add \"HKLM\\Software\\Microsoft\\Windows Defender Security Center\\Notifications\" /v \"DisableNotifications\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Notifications", Description = "Disable Enhanced Defender Notifications (HKLM)", RegCommand = "reg add \"HKLM\\Software\\Policies\\Microsoft\\Windows Defender Security Center\\Notifications\" /v \"DisableEnhancedNotifications\" /t REG_DWORD /d 1 /f" },

                // ===================== PRIVACY & SECURITY =====================
                new RegistryTweak { Category = "Privacy & Security", Description = "Block AAD Workplace Join Prompts", RegCommand = "reg add \"HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\WorkplaceJoin\" /v \"BlockAADWorkplaceJoin\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Windows Error Reporting (HKCU)", RegCommand = "reg add \"HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Error Reporting\" /v \"Disabled\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Content Delivery (Ads)", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"ContentDeliveryAllowed\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Subscribed Content (Ads)", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"SubscribedContentEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Feature Management (Promotions)", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"FeatureManagementEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Soft Landing Tips", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"SoftLandingEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable OEM Pre-Installed Apps", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"OemPreInstalledAppsEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable MS Suggested Pre-Installed Apps", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"PreInstalledAppsEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Pre-Installed App Tracking", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"PreInstalledAppsEverEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Silent App Installations", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"SilentInstalledAppsEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Rotating Lock Screen", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"RotatingLockScreenEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Lock Screen Overlay Tips", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"RotatingLockScreenOverlayEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Advertising ID Tracking (CurrentVersion)", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo\" /v \"Enabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Store Advertising ID Tracking", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\CPSS\\Store\\AdvertisingInfo\" /v \"Value\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Advertising ID Tracking (Policies)", RegCommand = "reg add \"HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\AdvertisingInfo\" /v \"DisabledByGroupPolicy\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Opt-Out of HTTP Accept Language Tracking", RegCommand = "reg add \"HKCU\\Control Panel\\International\\User Profile\" /v \"HttpAcceptLanguageOptOut\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Enable App Tracking for Start Menu", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v \"Start_TrackProgs\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Settings Account Notifications", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\SystemSettings\\AccountNotifications\" /v \"EnableAccountNotifications\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Opt-Out of Online Speech Privacy Policy", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Speech_OneCore\\Settings\\OnlineSpeechPrivacy\" /v \"HasAccepted\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Remove Online Speech Recognition Policy", RegCommand = "reg delete \"HKCU\\SOFTWARE\\Policies\\Microsoft\\InputPersonalization\" /v \"AllowInputPersonalization\" /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Narrator Online Services", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Narrator\\NoRoam\" /v \"OnlineServicesEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Restrict Implicit Text Collection", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\InputPersonalization\" /v \"RestrictImplicitTextCollection\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Contact Harvesting", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\InputPersonalization\\TrainedDataStore\" /v \"HarvestContacts\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Hide DiagTrack Toast Notifications", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Diagnostics\\DiagTrack\" /v \"ShowedToastAtLevel\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Telemetry (Policies HKCU)", RegCommand = "reg add \"HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection\" /v \"AllowTelemetry\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Telemetry (CurrentVersion HKCU)", RegCommand = "reg add \"HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection\" /v \"AllowTelemetry\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Application Telemetry (AIT)", RegCommand = "reg add \"HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat\" /v \"AITEnable\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Inking and Typing Diagnostics", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Input\\TIPC\" /v \"Enabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Tailored Experiences Data (CurrentVersion)", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Privacy\" /v \"TailoredExperiencesWithDiagnosticDataEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Remove Tailored Experiences Cloud Policy", RegCommand = "reg delete \"HKCU\\Software\\Policies\\Microsoft\\Windows\\CloudContent\" /v \"DisableTailoredExperiencesWithDiagnosticData\" /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Feedback Notifications (HKCU)", RegCommand = "reg add \"HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection\" /v \"DoNotShowFeedbackNotifications\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Windows Timeline / Activity History (HKCU)", RegCommand = "reg add \"HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\" /v \"PublishUserActivities\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Timeline Suggestions (353698)", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v \"SubscribedContent-353698Enabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Local Search History", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\SearchSettings\" /v \"IsDeviceSearchHistoryEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Dynamic Search Box Suggestions", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\SearchSettings\" /v \"IsDynamicSearchBoxEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable MSA Cloud Search", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\SearchSettings\" /v \"IsMSACloudSearchEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable AAD Cloud Search", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\SearchSettings\" /v \"IsAADCloudSearchEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Cortana in Search (HKCU)", RegCommand = "reg add \"HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v \"AllowCortana\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Remove Location Disablement Policy (Restore Access)", RegCommand = "reg delete \"HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\LocationAndSensors\" /v \"DisableLocation\" /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Block OneDrive Auto-Backup (Known Folder Move)", RegCommand = "reg add \"HKCU\\SOFTWARE\\Policies\\Microsoft\\OneDrive\" /v \"KFMBlockOptIn\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable UAC Secure Desktop Prompt", RegCommand = "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\" /v \"PromptOnSecureDesktop\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable UAC Prompt for Admins", RegCommand = "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\" /v \"ConsentPromptBehaviorAdmin\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Block 'Allow my organization to manage my device' Prompt", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WorkplaceJoin\" /v \"BlockAADWorkplaceJoin\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Prevent Automatic BitLocker Encryption", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\BitLocker\" /v \"PreventDeviceEncryption\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable WiFi Sense / HotSpot Reporting", RegCommand = "reg add \"HKLM\\Software\\Microsoft\\PolicyManager\\default\\WiFi\\AllowWiFiHotSpotReporting\" /v \"Value\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Auto-Connect to WiFi Hotspots", RegCommand = "reg add \"HKLM\\Software\\Microsoft\\PolicyManager\\default\\WiFi\\AllowAutoConnectToWiFiSenseHotspots\" /v \"Value\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Automatic System Maintenance", RegCommand = "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\Maintenance\" /v \"MaintenanceDisabled\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Windows Error Reporting", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Error Reporting\" /v \"Disabled\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Remote Assistance", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Remote Assistance\" /v \"fAllowToGetHelp\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Advertising ID Tracking", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\AdvertisingInfo\" /v \"DisabledByGroupPolicy\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Remove Online Speech Recognition", RegCommand = "reg delete \"HKLM\\SOFTWARE\\Policies\\Microsoft\\InputPersonalization\" /v \"AllowInputPersonalization\" /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Telemetry Data Collection", RegCommand = "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection\" /v \"AllowTelemetry\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Application Telemetry", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat\" /v \"AITEnable\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Tailored Experiences (Ads & Tips)", RegCommand = "reg delete \"HKLM\\Software\\Policies\\Microsoft\\Windows\\CloudContent\" /v \"DisableTailoredExperiencesWithDiagnosticData\" /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Feedback Notifications", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection\" /v \"DoNotShowFeedbackNotifications\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Windows Timeline (Activity History)", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\" /v \"PublishUserActivities\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Disable Cortana Search", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v \"AllowCortana\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Deny Location Access to Apps", RegCommand = "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\location\" /v \"Value\" /t REG_SZ /d \"Deny\" /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Deny App Diagnostic Access", RegCommand = "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\appDiagnostics\" /v \"Value\" /t REG_SZ /d \"Deny\" /f" },
                new RegistryTweak { Category = "Privacy & Security", Description = "Prevent OneDrive Auto-Backup (Documents/Pictures)", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\OneDrive\" /v \"KFMBlockOptIn\" /t REG_DWORD /d 1 /f" },

                // ===================== SOUND SETTINGS =====================
                new RegistryTweak { Category = "Sound", Description = "Disable Windows Startup Sound", RegCommand = "reg add \"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Authentication\\LogonUI\\BootAnimation\" /v \"DisableStartupSound\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Sound", Description = "Disable Voice Activation Listening", RegCommand = "reg add \"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\SpeechOneCore\\Settings\" /v \"AgentActivationEnabled\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Sound", Description = "Auto-Lower Volume on Communication (Ducking)", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Multimedia\\Audio\" /v \"UserDuckingPreference\" /t REG_DWORD /d 3 /f" },
                new RegistryTweak { Category = "Sound", Description = "Disable Narrator Audio Ducking", RegCommand = "reg add \"HKCU\\Software\\Microsoft\\Narrator\\NoRoam\" /v \"DuckAudio\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Sound", Description = "Disable Accessibility Activation Sounds", RegCommand = "reg add \"HKCU\\Control Panel\\Accessibility\" /v \"Sound on Activation\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Sound", Description = "Disable Accessibility Warning Sounds", RegCommand = "reg add \"HKCU\\Control Panel\\Accessibility\" /v \"Warning Sounds\" /t REG_DWORD /d 0 /f" },

                // ===================== WINDOWS UPDATE =====================
                new RegistryTweak { Category = "Updates", Description = "Disable Delivery Optimization (P2P Downloads)", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\DeliveryOptimization\" /v \"DODownloadMode\" /t REG_DWORD /d 99 /f" },
                new RegistryTweak { Category = "Updates", Description = "Opt-Out of Continuous Innovation Rollouts", RegCommand = "reg add \"HKLM\\SOFTWARE\\Microsoft\\WindowsUpdate\\UX\\Settings\" /v \"IsContinuousInnovationOptedIn\" /t REG_DWORD /d 0 /f" },
                new RegistryTweak { Category = "Updates", Description = "Disable Auto-Reboot with Logged On Users", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU\" /v \"NoAutoRebootWithLoggedOnUsers\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Updates", Description = "Exclude Driver Updates from Windows Update", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\" /v \"ExcludeWUDriversInQualityUpdate\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Updates", Description = "Disable Auto-Download for Microsoft Store Apps", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\WindowsStore\" /v \"AutoDownload\" /t REG_DWORD /d 2 /f" },

                // ===================== EXPLORER & UI =====================
                new RegistryTweak { Category = "Explorer", Description = "Enable Long File Paths (>260 chars)", RegCommand = "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\FileSystem\" /v \"LongPathsEnabled\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Explorer", Description = "Hide 3D Objects Folder in This PC", RegCommand = "reg delete \"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\MyComputer\\NameSpace\\{0DB7E03F-FC29-4DC6-9020-FF41B59E513A}\" /f" },
                new RegistryTweak { Category = "Explorer", Description = "Hide Home Folder in Navigation Pane", RegCommand = "reg delete \"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Desktop\\NameSpace\\{f874310e-b6b7-47dc-bc84-b9e6b38f5903}\" /f" },
                new RegistryTweak { Category = "Explorer", Description = "Hide Gallery Folder in Navigation Pane", RegCommand = "reg delete \"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Desktop\\NameSpace\\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}\" /f" },

                // ===================== START MENU & TASKBAR =====================
                new RegistryTweak { Category = "Start & Taskbar", Description = "Hide Recommended Section in Start Menu", RegCommand = "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Explorer\" /v \"HideRecommendedSection\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Start & Taskbar", Description = "Disable Web Search in Start Menu", RegCommand = "reg add \"HKLM\\Software\\Policies\\Microsoft\\Windows\\Explorer\" /v \"DisableSearchBoxSuggestions\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Start & Taskbar", Description = "Hide Meet Now / Chat Button", RegCommand = "reg add \"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\" /v \"HideSCAMeetNow\" /t REG_DWORD /d 1 /f" },
                new RegistryTweak { Category = "Start & Taskbar", Description = "Disable News and Interests (Widgets)", RegCommand = "reg add \"HKLM\\Software\\Policies\\Microsoft\\Dsh\" /v \"AllowNewsAndInterests\" /t REG_DWORD /d 0 /f" }
            };
        }

        public static List<ServiceTweak> GetAvailableServices()
        {
            return new List<ServiceTweak>
            {
                new ServiceTweak { ServiceName = "AJRouter", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "ALG", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "AppIDSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "AppMgmt", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "AppReadiness", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "AppVClient", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "AppXSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "Appinfo", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "AssignedAccessManagerSvc", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "AudioEndpointBuilder", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "AudioSrv", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "AxInstSV", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "BDESVC", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "BFE", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "BITS", StartupType = "AutomaticDelayedStart" },
                new ServiceTweak { ServiceName = "BTAGService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "BcastDVRUserService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "BluetoothUserService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "BrokerInfrastructure", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "Browser", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "BthAvctpSvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "BthHFSrv", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "CDPSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "CDPUserSvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "COMSysApp", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "CaptureService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "CertPropSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "ClipSVC", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "ConsentUxUserSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "CoreMessagingRegistrar", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "CredentialEnrollmentManagerUserSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "CryptSvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "CscService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "DPS", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "DcomLaunch", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "DcpSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "DevQueryBroker", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "DeviceAssociationBrokerSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "DeviceAssociationService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "DeviceInstall", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "DevicePickerUserSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "DevicesFlowUserSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "Dhcp", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "DiagTrack", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "DialogBlockingService", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "DispBrokerDesktopSvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "DisplayEnhancementService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "DmEnrollmentSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "Dnscache", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "EFS", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "EapHost", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "EntAppSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "EventLog", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "EventSystem", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "FDResPub", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "Fax", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "FontCache", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "FrameServer", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "FrameServerMonitor", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "GraphicsPerfSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "HomeGroupListener", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "HomeGroupProvider", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "HvHost", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "IEEtwCollectorService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "IKEEXT", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "InstallService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "InventorySvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "IpxlatCfgSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "KeyIso", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "KtmRm", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "LSM", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "LanmanServer", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "LanmanWorkstation", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "LicenseManager", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "LxpSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "MSDTC", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "MSiSCSI", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "MapsBroker", StartupType = "AutomaticDelayedStart" },
                new ServiceTweak { ServiceName = "McpManagementService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "MessagingService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "MicrosoftEdgeElevationService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "MixedRealityOpenXRSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "MpsSvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "MsKeyboardFilter", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "NPSMSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "NaturalAuthentication", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "NcaSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "NcbService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "NcdAutoSetup", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "NetSetupSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "NetTcpPortSharing", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "Netlogon", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "Netman", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "NgcCtnrSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "NgcSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "NlaSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "OneSyncSvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "P9RdrService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "PNRPAutoReg", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "PNRPsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "PcaSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "PeerDistSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "PenService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "PerfHost", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "PhoneSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "PimIndexMaintenanceSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "PlugPlay", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "PolicyAgent", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "Power", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "PrintNotify", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "PrintWorkflowUserSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "ProfSvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "PushToInstall", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "QWAVE", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "RasAuto", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "RasMan", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "RemoteAccess", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "RemoteRegistry", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "RetailDemo", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "RmSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "RpcEptMapper", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "RpcLocator", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "RpcSs", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "SCPolicySvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SCardSvr", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SDRSVC", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SEMgrSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SENS", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "SNMPTRAP", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SSDPSRV", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SamSs", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "ScDeviceEnum", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "Schedule", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "SecurityHealthService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "Sense", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SensorDataService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SensorService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SensrSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SessionEnv", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SharedAccess", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SharedRealitySvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "ShellHWDetection", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "SmsRouter", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "Spooler", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "SstpSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "StiSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "StorSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "SysMain", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "SystemEventsBroker", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "TabletInputService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "TapiSrv", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "TermService", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "Themes", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "TieringEngineService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "TimeBroker", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "TimeBrokerSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "TokenBroker", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "TrkWks", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "TroubleshootingSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "TrustedInstaller", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "UI0Detect", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "UdkUserSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "UevAgentService", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "UmRdpService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "UnistoreSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "UserDataSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "UserManager", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "UsoSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "VGAuthService", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "VMTools", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "VSS", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "VacSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "VaultSvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "W32Time", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WEPHOSTSVC", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WFDSConMgrSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WMPNetworkSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WManSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WPDBusEnum", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WSAIFabricSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WSService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WSearch", StartupType = "AutomaticDelayedStart" },
                new ServiceTweak { ServiceName = "WaaSMedicSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WalletService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WarpJITSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WbioSrvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "Wcmsvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "WcsPlugInService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WdNisSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WdiServiceHost", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WdiSystemHost", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WebClient", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "Wecsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WerSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WiaRpc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WinDefend", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "WinHttpAutoProxySvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WinRM", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "Winmgmt", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "WlanSvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "WpcMonSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WpnService", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "WpnUserService", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "XblAuthManager", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "XblGameSave", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "XboxGipSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "XboxNetApiSvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "autotimesvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "bthserv", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "camsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "cbdhsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "cloudidsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "dcsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "defragsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "diagnosticshub.standardcollector.service", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "diagsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "dmwappushservice", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "dot3svc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "edgeupdate", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "edgeupdatem", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "embeddedmode", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "fdPHost", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "fhsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "gpsvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "hidserv", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "icssvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "iphlpsvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "lfsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "lltdsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "lmhosts", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "msiserver", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "netprofm", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "nsi", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "p2pimsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "p2psvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "perceptionsimulation", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "pla", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "seclogon", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "shpamsvc", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "smphost", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "spectrum", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "sppsvc", StartupType = "AutomaticDelayedStart" },
                new ServiceTweak { ServiceName = "ssh-agent", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "svsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "swprv", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "tiledatamodelsvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "tzautoupdate", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "uhssvc", StartupType = "Disabled" },
                new ServiceTweak { ServiceName = "upnphost", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "vds", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "vm3dservice", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "vmicguestinterface", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "vmicheartbeat", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "vmickvpexchange", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "vmicrdv", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "vmicshutdown", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "vmictimesync", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "vmicvmsession", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "vmicvss", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "vmvss", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "wbengine", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "wcncsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "webthreatdefsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "webthreatdefusersvc", StartupType = "Automatic" },
                new ServiceTweak { ServiceName = "wercplsupport", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "wisvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "wlidsvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "wlpasvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "wmiApSrv", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "workfolderssvc", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "wscsvc", StartupType = "AutomaticDelayedStart" },
                new ServiceTweak { ServiceName = "wuauserv", StartupType = "Manual" },
                new ServiceTweak { ServiceName = "wudfsvc", StartupType = "Manual" }
            };
        }
    }
}